### ISSUE TITLE
section 6.2.2- Adaptive Streaming Playback- Presentation Delay

### ISSUE THREAD

**Issue by YasserSyed** [irajs/CMAF#10]
Is the presentation delay set individually by each player? How much can this vary? How is this minimized for a live stream service?

**Comment by ghost** [comment]
Yes, each player controls its presentation delay.  CMAF doesn't specify most aspects of players and manifests, including presentation delay, buffer management, adaptive algorithms, server/client sync, etc.
A manifest can promise a maximum Segment duration that a player can factor into the delay it selects. Typically, live delay ranges from 2 to 4 Segment durations.
Shorter Segments and delivery of Segments in Chunks can reduce latency.  But, other factors need to be considered, such as network jitter (some Segments edge cached, others from an origin server), client/server clock error, response time of the adaptive algorithm and related bitrate gradient between Tracks in a Switching Set (a small gradient allows frequent adjustment that appears seamless).  Operating at a lower bitrate relative to the network bandwidth allows a very short buffer to be managed.  Short CVSs and low latency switching algorithms trade lower video quality for low latency.

**Comment by dwsinger** [comment]
filed on w15947 (San Diego output)

**Comment by dwsinger** [comment]
No change proposed, as player behavior is out of scope and more specified by the streaming protocol (DASH, HLS) environment (3GPP, managed or unmanaged network), implementation (e.g. amount of buffer memory) and so on.
