### ISSUE TITLE
CMAF URL 

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#11]
Define "Segment identifier" which is defined as URL or possibly with a URL with byte range address.

**Comment by mwatson2** [comment]
The intention is then to use this term wherever we mention a "URI" for a CMAF Segment.

**Comment by cconcolato** [comment]
Can someone clarify why this concept is needed? 

A URL or URL with byte range or any other locator is a delivery concept. It should be up to the manifest format to choose what locator it want to use. 

I heard also that the concept is useful in Switching Sets to identify to switchable segments but the number of the segment or the time range suffices.

**Comment by ghost** [comment]
CMAF defines media objects (CMAF Fragments) that are encoded in such a way to form a large number of valid Presentations, and an infinite number of “invalid” presentations where the content won’t decode, isn’t synchronized, isn’t related by Switching Set, Selection Set, or Presentation.

The media encoding determines the valid sequences and combinations of CMAF Fragments, not manifests created later to describe the media.  The media is “source of truth”.

The process of “late binding” CMAF Fragments into a Presentation depends on encoders, servers, CDNs, and manifests identifying the same media object. How that is done is flexible, but shared object identification is a requirement of the Application Framework.

Movie Fragments need to be addressed by packagers, origin servers, CDNs, proxy caches, manifests, etc. by the same URI to compose the intended Presentation as encoded.  Each CMAF Fragment has an identity that must be preserved, but the actual identifier used is flexible as long as it preserves the identity throughout the application from encoding to presentation.  Using multiple identifiers for the same object can result in duplicate caching, etc., but is an implementation choice as long as the identity of each object encoded is maintain in the Presentation.

The presentation model is entirely different from an ISO Media file, where a presentation is early bound as tracks synchronized and selected from within a single file, and a single movie box and movie timeline describe all the movie fragments and their composition into a presentation.

There needs to be a validity test for manifests that they result in a Presentation that is selected and synchronized according to the Tracks, Selection Sets, and Switching Sets encoded as a Presentation.  There is no physical binding, they are linked by media object identity, and eventually some identifier.

Kilroy Hughes | Senior Digital Media Architect |Windows Azure Media Services | Microsoft Corporation
[cid:image001.png@01CDABBA.71FD8800]http://www.windowsazure.com/media

**Comment by dwsinger** [comment]
defined as "CMAF Resource Identifier" in M38228-V2 (May)
