### ISSUE TITLE
Shorten the Introduction

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#13]
1. too descriptive and lengthy. Please shorten the introduction
2. remove the how, only include what and why.
3. Use some of requirement document to add it.
4. Add a paragraph that the intend of this spec is for delivery (between service provider to devices).

**Comment by dwsinger** [comment]
filed on m38228/v1

**Comment by ghost** [comment]
Introduction shortened.  Explanations consolidated in Section 6 v3.

**Comment by ghost** [comment]
Short intro provided by Dolan based on Requirements:
Several MPEG technologies have been adopted for the majority of video delivered over the Internet and other IP networks (cellular, cable, broadcast, etc.). Various organizations have taken MPEG’s core coding, file format and system standards, and combined them into their own specifications for their specific applications. While these specifications share major common parts, their differences result in both unnecessary duplication of engineering effort, and duplication of identical content in slightly different formats and increases/duplicates storage. The industry would benefit if an application consortia could reference a single MPEG specification (a “common format”) that would allow a single media encoding to work defines a common format to use across many applications and devices.
The primary common requirements were identified as follows:
1.  Streaming delivery mechanism agnostic, but specifically supporting the needs of both DASH and HLS.
2.  Seamless adaptive switching of tracks encoded with different bitrates, frame rates, and video resolutions.
3.  Broadcast, multicast and broadband delivery, plus hybrid delivery (2 or more of these concurrently) 
4.  Low latency live streaming
5.  Efficient CDN delivery specifically considering:
a.  large-scale video distribution over the Internet, and other networks such as 4G MBMS and 5G
b.  uniform identification of each media segment by URI (and possible byte range) for efficient caching and reuse.
6.  Media codecs and profiles defined that are in wide commercial deployment in adaptive steaming systems.
