### ISSUE TITLE
Scope

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#15]
- Have few spec/two paragraph of the scope
- also says what's out of scope
  -Need a figure to show the application model and the normative scope of this spec.
- make it clear how the manifest's requirement fits in the scope of this requirement.
  https://github.com/irajs/CMAF/issues/new

**Comment by cconcolato** [comment]
What about a scope diagram like this one:
![image](https://cloud.githubusercontent.com/assets/1830314/14489169/0b1a0364-016c-11e6-8df7-61af8120ca4e.png)

**Comment by dwsinger** [comment]
New scope diagram in M38228-V2 (May)

**Comment by irajs** [comment]
Still no agreement on the diagram

**Comment by irajs** [comment]
Addressed in CD.
