### ISSUE TITLE
Section 2: acronym of ISO file should be ISOBMFF

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#16]

**Comment by dwsinger** [comment]
done in M38228-V2 (May)

**Comment by irajs** [comment]
still open

**Comment by dwsinger** [comment]
"still open" -- so, close it if you think it done (I believe it is), or say what problem still exists?

**Comment by ghost** [comment]
There were still instances of “ISOM” in the document that had not been changed to “ISOBMFF”, so search and replace is needed.

Kilroy Hughes | Senior Digital Media Architect |Windows Azure Media Services | Microsoft Corporation
[cid:image001.png@01CDABBA.71FD8800]http://www.windowsazure.com/media

**Comment by dwsinger** [comment]
It seems some editors have used "hyperlink" and some "bookmark" and only the bookmarks update when F9 is pressed. We need to use bookmarks as they update
