### ISSUE TITLE
3.1 Terms

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#17]
1. Required: not needed. Remove and use the term SHALL or SHOULD.
2. there are cases in document using "required" with lowercase r. It should be changed to SHALL or SHOULD.
3. I-Picture is not used. can be removed.
4. Since Video profile is only used in Annex A, it can be removed here. 
5. a term definition should not describe requirement for that term but just describe the term itself. 
6. Sync Sample: a simple phrase  refer to its definition in Part 12 rather than defining it here.
7. CMAF Container is not defined. Either define it or change the text.
8.

**Comment by irajs** [comment]
Suggestion: Use "CMAF Package" instead of "CMAF Segment"

**Comment by dwsinger** [comment]
Required is no longer a defined term.  But A.3 still uses it.
I-picture removed.
Video Profile is indeed only used in the annex.
I-picture has gone. sync sample is not defined here any more.

all in M38228-V2 (May)

we have work to do on 'required' and 'CMAF container'

**Comment by dwsinger** [comment]
'required' handled post /v2 (May 19th).

**Comment by dwsinger** [comment]
CMAF Container
CMAF Segment or Fragment that conforms to the CMAF file format requirements

at least, a first stab, handled post /v2 (May 19th).

**Comment by irajs** [comment]
check the use of Required and Required media profile.
Also check if term "sync sample" is needed.
Please remove "CMAF container" if possible.

**Comment by irajs** [comment]
All addressed in CD.
