### ISSUE TITLE
3.2 Abbreviation

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#18]
1. Add SAP
2. AU: access unit
3. CVS: don't redefine it.
4. CMAF is missing
5. Remove IDR since it is not used. The only case used can be replaced with SAP.

**Comment by dwsinger** [comment]
SAP defined.
AU still mis-defined.
CVS is still re-defined.
CMAF defined
IDR deleted.

in M38228-V2 (May)

**Comment by dwsinger** [comment]
filed on m38228/v1

**Comment by dwsinger** [comment]
AU corrected. CVS defined as defined by the video format. all in post-/v2 (May 17 edit).
