### ISSUE TITLE
CMFHD typo

### ISSUE THREAD

**Issue by cconcolato** [irajs/CMAF#37]
The acronym CMFHD is used in http://cconcolato.github.io/cmaf/index.html#h-cmaf-presentation-profiles but not defined and not relevant here. Probably a typo.

**Comment by dwsinger** [comment]
filed on m38228/v1; CMFHD occurs only once, in A.1. delete?

**Comment by dwsinger** [comment]
CMFHD is the name of a presentation profile. handled post-/v2 (May 17 edit).
