### ISSUE TITLE
Annex A.1 and A.4

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#38]
Both VTT and IMSC V1 text profile are required in CMAF.
Add a new row in the table for IMSC V1 image profile, as optional track.

Also add a sentence in hypothetical player model that it can support either VTT or IMSC1 format for subtitle.

**Comment by poolec** [comment]
We also agreed to recommend that manifests should provide means to indicate the preferred subtitle format where more than one is provided and that only one format may fully represent the content provider's intent for subtitle presentation.  That might be best placed in 11.1 (the subtitle introduction).

**Comment by dwsinger** [comment]
Addressed in V2(May). "CMAF specifies two required subtitle profiles, WebVTT Core and TTML IMSC1, "

Except the Hypo player model is not media-coding-specific.
