### ISSUE TITLE
7.3 through 7.3.3

### ISSUE THREAD

**Issue by krasimirkolarov** [irajs/CMAF#40]
- fix levels for "sgpd" and "elng"
- remove last sentence in the first paragraph and rewrite the paragraph
- make the table informative. For any box that is not in the text it should have normative reference
- check all references (external and internal)
- differentiate "optional" and "conditionally mandated" 
- rewrite 7.3.2 as one sentence that the following sections define the CMAF structure
- in 7.3.3 
  - edit first sentence
  - edit second paragraph by just leaving the last sentence
  - remove second constraint (already defined in ISOBMFF) and check the rest
  - remove Figure 2 and refer to Table 1 as needed
  - reply "as specify by" with "as constrained with"
  - remove paragraph about "Free Box"
  - the last paragraph should go to Section 6

**Comment by sambushell** [comment]
Addressed in May 2016 revision.

**Comment by dwsinger** [comment]
done in M38228-V2 (May)

**Comment by irajs** [comment]
Make sure that the table and sections do not have redundant information.
Also fix the broken references.

referenced section in the ftype paragraph is not correct.

**Comment by irajs** [comment]
Addressed in CD.
