### ISSUE TITLE
WebVTT cue and Segment boundaries

### ISSUE THREAD

**Issue by cconcolato** [irajs/CMAF#41]
The following text is unclear:
http://cconcolato.github.io/cmaf/index.html#webvtt

> Any WebVTT cue that crosses a CMAF Segment boundary (i.e. which starts before the Segment starts and/or ends after the Segment ends) shall be present in that Segment, and shall indicate the entire time range of the cue, even when it lies outside of the Segment boundary.

"that segment" means the first, the second or both segments ?
In WebVTT there is no difference between the duration of a sample and of a cue. How can the cue indicate a time range that is different from the fragment/segment boundary?

**Comment by dwsinger** [comment]
not addressed yet in M38228-V2 (May)

**Comment by dwsinger** [comment]
handled post-/v2 (May 17 edit).
