### ISSUE TITLE
7.3.4 and 7.3.5

### ISSUE THREAD

**Issue by krasimirkolarov** [irajs/CMAF#42]
7.3.4
- paragraph 1 - remove after "because ..."
- edit the second paragraph - remove the first part, leave "CMAF header SHALL be sufficient"
- move the "Note" ?
- reword based on the change to CMAF Tracks
- delete the paragraph for CMAF Compatible Track
- add a note that Matadata tracks are supported (in the right section)
- delete the paragraph after the "Note"
- accept m38235 with Option A reworded to not impose constraint on the players

7.3.5
- add edit list to reflect in 5. and 11.
- edit bullet 6. - David will rewrite
- improve the sentence in bullet 9. Delete thes second sentence

**Comment by dwsinger** [comment]
mostly done in M38228-V2 (May); the long Note remains (and is too long).

**Comment by dwsinger** [comment]
Long note is gone, now in an informative Annex (CD)
