### ISSUE TITLE
7.3.6 and 7.3.10

### ISSUE THREAD

**Issue by krasimirkolarov** [irajs/CMAF#43]
7.3.6 
- make the second paragraph a "Note", remove the "Shall", encourage contributions
- same for the last two paragraphs 

7.3.7
- bullet 1 is ISOBMFF Fragment not CMAF 
- follow up on segments vs. chunks
- should we allow segments to be reconstructed from the chunks

7.3.8
- paragraph 3 chnge SHALL to "is"
- move the "seamless switching" to Section 6
- replace "time stamp" with "time range"
- move "All CMAF Tracks in a ..." to bitstream switchable section (to be created)
- need "common header switching" concept; Selection Set and Switchable Sets
- track ID should stay the same

7.3.9
- paragraph 1 - "SHALL" goes to "are"

7.3.10
- last paragraph - remove first sentence; the rest goes to Section 6
- new paragraph - CMEF Presentation should conform to Appendix A1
- second paragraph is deifinition - change "SHALL" to have - combine and simplify
- remove the second to the last paragraph

**Comment by dwsinger** [comment]
mostly (all?) done in M38228-V2 (May)?

**Comment by dwsinger** [comment]
all addressed in the CD, we think
