### ISSUE TITLE
8

### ISSUE THREAD

**Issue by krasimirkolarov** [irajs/CMAF#46]
8.1
We need to work on the accuracy of the 3rd paragraph. It will be removed unless a better description is provided

8.2.1 - rename to "General constratints"
Add a paragraph to require either CBCS or CENC
In the second paragraph - change the paragraph into a descriptive part
8.2.2 becomes part of 8.2.1 (remove section heading and leave as a bullet)
last paragraph - UUID the contribution from Netflix - replace with 16 byte field and aligh with Common Encryption spec

8.2.3.1
- add "or equivalent" on first bullet 
- add "or equivalent" on second bullet and edit
- Note in the last paragraph - "requires" rather than "defines"; other edits as per Mark's contribution

8.2.3.2
take it off, it is referenced elsewhere

8.2.3.3
-synch with text in 8.1
- add "in some players" in the second paragraph
- first bullet in third paragraph - remove second sentence there
- last second of second bullet - remove

8.2.4
- first bullet take out "globally" and "initialization vectors"
- third bullet  - replace "all CMAF Tracks" with "within th scope of use"
- fourth bullet - instead of CMAF Switch Set to CMAF Common Header Switching Set

**Comment by dwsinger** [comment]
filed on m38228/v1

**Comment by dwsinger** [comment]
Not all addressed in V2(May)

**Comment by ghost** [comment]
Section 8 on DRM were revised in the CD per the above comments.
