### ISSUE TITLE
2nd draft: Section 9.2.2 Define Active picture area

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#49]
“The values of width and height SHALL indicate the active picture area of the video content without overscan and measured on a uniformly sampled square grid as specified…”

We need to clarify the tkhd width and height as being post clap, parameter set cropping, and pasp correction.  "Active picture area" is not defined. 

ACTION: Remove ‘active picture area’ rather and explain what is meant without creating a new definition. Term refers to the source content but does warrant a definition.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by ghost** [comment]
Modified to describe Height and Width in Track Header and sample entry sequence parameter sets, rather than the active area of the source video (Active Image).
