### ISSUE TITLE
Support of Live to VoD Case

### ISSUE THREAD

**Issue by YasserSyed** [irajs/CMAF#5]
Would like to understand how CMAF would support a live to VOD case.

**Comment by dwsinger** [comment]
filed on w15947 (San Diego output)

**Comment by ghost** [comment]
It's mostly Manifest functionality that is out of CMAF scope.  Fragments and Segments generated live can be stored, then synchronized in one or more Presentations by a Manifest that specifies the first video 'tfdt' time of a program being made available VOD, and its duration.  Similarly, the earliest audio and subtitle presentation times at that video 'tfdt' time need to be indicated by presentation time offsets. No modification of recorded Segments is necessary, unless "splice conditioning' is necessary to shorten a Segment by re-encoding the contained CVS to introduce a new SAP and repackage a Segment with that Fragment duration.
