### ISSUE TITLE
2nd draft: Section 9.2.2 spatial samples intended for presentation

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#50]
Comment 29 “The video elementary stream SHALL contain only spatial samples intended for presentation after SPS cropping parameters are applied in the decoder. The Clean Aperture box SHOULD NOT be present.”

 “spatial samples intended for presentation after SPS cropping parameters”. Examples in appendix. 

ACTION: “add diagram, showing the whole story.”

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by irajs** [comment]
Reviewed and still needs edits

**Comment by dwsinger** [comment]
"Reviewed and still needs edits" leaves the editors with no idea what's wrong or how to fix it

**Comment by ghost** [comment]
I took notes during the meeting at to the actual edits intended.

Kilroy Hughes | Senior Digital Media Architect |Windows Azure Media Services | Microsoft Corporation
[cid:image001.png@01CDABBA.71FD8800]http://www.windowsazure.com/media

**Comment by dwsinger** [comment]
added the phrase "after SPS cropping".  needs diagram?

**Comment by ghost** [comment]
Resolved in the CD. The text was revised to remove normative requirements on the content in the elementary stream ("SHALL contain only samples intended for presentation"), and changed to make functional statements about cropping, etc. specified by referenced codec and container normative references. That clarifies which samples are presented so authors can infer how to encode samples intended for presentation, but does not create an untestable requirement on content.
