### ISSUE TITLE
2nd draft: Section 9.2.2 Height and width in sample entry

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#51]
Comment 31: “The normalized Presentation height SHALL be the number of vertical samples after SPS cropping parameters are subtracted from the encoded frame height indicated by the SPS. The height field of the visual sample entry SHALL be set to number of encoded vertical samples after cropping.”

Height and width in sample entry should point to normative under sample entry. Seems to contradict part 15. Is already normatively referenced in Part 15, so should reference and not restate.

ACTION: Change to “as stated in the section about visual sample entry”.

ACTION: Clarify parameters in parameter sets Video access unit > video sample. Clarify filler data NAL and SEI with reference. Clarify access unit of type 'avc1' etc. is the stream type, not access unit type.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by irajs** [comment]
still open. check implementation.

**Comment by ghost** [comment]
Clarified in CD.
