### ISSUE TITLE
2nd draft: Section 9.2.2 Intended video orientation

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#52]
Note in 9.2.2, questions about the client-side behavior 'expected' (there is also a 'must' in a note, which we need to fix). What does the source do if we cannot trust that the client respects the matrix? (Nothing; it's the client's job.)  No change.  Reword to say that reflect the 'intended' video orientation. "indicates the intended video orientation" (it's a non-testable SHALL).

ISSUE: “The value of the matrix field SHALL reflect the video orientation. Non-identity matrices SHALL be rotations in multiples of 90 degrees.”

Are clients expected or required to support that. What is meant by “reflect the video orientation”
Major goal of this section is to indicate the only allowed – 90-degree rotation, ISO allows any arbitrary to be applied. 

Indicates the intended video orientation. Remove SHALL.

ACTION: Change phrase to “intended video orientation”.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
done in CD
