### ISSUE TITLE
2nd draft: Section 9.2.3 SPS and Sample Entry issue

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#53]
Comment 32: “width and height field values equal to the largest cropped horizontal and vertical sample counts in any Sequence Parameter Set in the track (only one in the case of 'avc1' or 'hvc1')”

Does 'in a track' include the sample entry? (yes).  Why 'only one' SPS in avc1 and hvc1? Is that one SPS or one Sample Entry, or both?  This is 'only one sample entry' not 'only one SPS in the sample entry'. 

ACTION: Clarify SPS and Sample Entry issue.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by ghost** [comment]
Reworded to say SPS referenced by video slices to cover both cases where the parameter set index in the video references inband or sample entry stored SPS. 
Yes, in the added case of 'avc1' video, the sample entry can have more that one parameter set actually referenced.  If only used for initialization, in the 'avc3' case, only the first parameter set is used, and others referenced within each CVS.

**Comment by irajs** [comment]
Decoder configuration record, 1st bullet: change it to SHOULD signal the lowest or SHALL the signal the highest, whatever make sense.

**Comment by ghost** [comment]
Done.
