### ISSUE TITLE
2nd draft:  Section 9.2.3 a single parameter set for decoder and display initialization

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#54]
Comment 33: “SHALL contain a single parameter set for decoder and display initialization, for a Visual Sample Entry with codingname 'avc3' or 'hev1', (SPS and PPS NALs for AVC Video, or VPS, SPS, and PPS NALs for HEVC Video). Each video sample in the CMAF Track SHALL reference SPS and PPS NALs stored in its CMAF video Segment and Coded Video Sequence”

Flip the sentences over, so the contrast is clearer. The inline parameter set case has one parameter in the sample entry, where we can initialize.

We need a lot of clarification of what the parameter sets in the sample entry say for the in-line case.  So, max level. 'Most complex' profile?  What about the VUI? 

ACTION: Needs much more detail.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
clarified in CD
