### ISSUE TITLE
2nd draft:  Section 9.2.3 A single SPS NAL unit cannot contain multiple parameter sets

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#55]
Comment 34: “SHALL contain a single decoding parameter set, for a Visual Sample Entry with codingname 'avc1' or 'hvc1', (SPS and PPS NALs for AVC Video; VPS, SPS, and PPS NALs for HEVC Video). Each video sample in the CMAF Track SHALL reference this parameter set in the sample entry”

A single SPS NAL unit cannot contain multiple parameter sets. Can contain multiple picture parameter sets.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by irajs** [comment]
Remove the word "single" or remove the whole bullet.

**Comment by dwsinger** [comment]
phrase no longer appears in the CD
