### ISSUE TITLE
2nd draft:  Section 9.2.4:  defintion for Picture access unit

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#56]
Comment 35: The term is used without definition. 

ACTION: add definition of Picture Access Unit

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by irajs** [comment]
move picture access unit section to AVC and HEVC sections. If it is a should, it doesn't need further constraints than what Part 15 has.

**Comment by dwsinger** [comment]
Fixed in study of CD

"Picture Access Unit" no longer occurs.  Access Unit is a defined term of the underlying coding spec (AVC or HEVC).
