### ISSUE TITLE
2nd draft:  Section 9.2.4/ meaning of bitstream padding

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#57]
Comment 37: “Access Units of type 'avc3'and 'hev1' MAY retain bitstream padding and SEI messages that would change hypothetical reference decoder bitstream conformance if such conformance is necessary, such as the case where bitstreams are to be repackaged and conformance tested in MPEG-2 Transport Streams.”

What is meant by bitstream padding?

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
done in the CD
