### ISSUE TITLE
2nd draft: Section 9.2.5  Does SAP mean (also) signaling)?

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#58]
Comment 38: “A stream access point (SAP) type 1, 2, or 3 as defined by [ISOVIDEO] SHOULD occur approximately every 2 seconds or less within a Video Track for consistent random access.”

Thomas view is that SAP only exists by signaling. The editor’s intent is, in addition to requirement at start of segment, that this be an independently decodable frame. And expressed in a codec-independent way, as defined in Part 12. 

Thomas claims SAP is system level signaling.  Kilroy claims it is a functional description of sample dependency.

ACTION: Thomas should provide a contribution?

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by ghost** [comment]
The recommendation on adding frequent stream access points was clarified. Issue will be closed pending evidence of a problem in the ISOBMFF references to SAP types.

**Comment by irajs** [comment]
1. change the reference to Part 12.

**Comment by dwsinger** [comment]
now in 9.2.4.4, change ISOVIDEO to part 12
