### ISSUE TITLE
2nd draft:  Section 9.2.3.1  Clarify the slice header contains the parameter set index 

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#59]
Comment 39:” The values of the following fields SHOULD NOT change throughout a CMAF Track” 

seq_parameter_set_id

Resolve locally from slice header with the parameter index. Within a segment there is an SPS locally, it has to resolve to the local sequence parameter set, 

Clarify the slice header contains the parameter set index - clarify Constrain frame packing Video is appropriate for presentation on a display which uses the electro-optic transfer function specified in [R1886] with a peak luminance of 100 cd/m2 in a reference viewing environment that complies with [R2035].

ACTION: Need to clarify that this is in the slice header

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
9.3.2.2.1 in the CD.

**Comment by dwsinger** [comment]
Deleted in the Study of CD:
” The values of the following fields SHOULD NOT change throughout a CMAF Track”

seq_parameter_set_id"

as this would be a consequence of requiring or recommending only a single SPS, and we don't. Also, this section is about the _contents_ of an SPS, not references to it.
