### ISSUE TITLE
SAP type of low latency Chunk

### ISSUE THREAD

**Issue by YasserSyed** [irajs/CMAF#6]
Given that several low latency chunks contains the same information, is there a restriction on SAP type for a low latency chunk?

**Comment by cconcolato** [comment]
I'm not sure what you mean by "several low latency chunks contains the same information". 

In my understanding, only the CMAF chunk corresponding to the time range of a CMAF segment has to start with a SAP of type 1 and 2. You may have SAP type 3 in the middle of this chunk or at the start or middle of other chunks. It may be good to recommend that it starts a chunk. 

That said, if you consider that the your entire chunked stream is only corresponding to a single CMAF segment, that means that only the first Chunk of the CMAF Track will start with a SAP 1 or 2.

**Comment by dwsinger** [comment]
lo-latency chunks have no restriction on containing a SAP at all, afaik, let alone a specific type.

**Comment by dwsinger** [comment]
filed on w15947 (San Diego output)

**Comment by dwsinger** [comment]
Inserted into the CD study 
"There is no restriction on the SAP type of the first sample in a CMAF Chunk (though the first chunk of a segment shares the requirement on the first sample in a segment, of course)."
