### ISSUE TITLE
2nd draft:  Section 9.2.3.1 SHALLs under SHOULDs

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#60]
Comment 40: SHALL and MUST constraints under SHOULD. And some SHOULD found in informational text. 

SHALL and MUST constraints are okay under SHOULD if qualified to ‘when present’. SHOULD in informational text should not happen.

ACTION: Make sure all uses of SHALL and MUST are correct in the referenced sections.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
simplified in the CD
