### ISSUE TITLE
2nd draft: Section 9.3.2.3  Remove redundant sentence on  value of the entropy_coding_mode_flag 

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#61]
Comment 41: “The value of the entropy_coding_mode_flag SHALL NOT change throughout a CMAF Track using an 'avc1' sample entry.” 
Single parameter set in the header – so this is a consequence rather than restriction. True for all, since they cannot change since only. Why mention this flag specifically? Check.

 (We need to write restricted case statements with the restriction first.  "Only bananas and pineapples SHALL be eaten, consumer, transported or otherwise considered if you are a monkey in Hawaii")

ACTION: remove the sentence

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
not done, as if this is a PPS constraint, there may be several, so it's not a factual statement.

**Comment by ghost** [comment]
Resolved, not fix, but clarify.
Multiple parameter sets are allowed in the sample entry, so the premise is not correct.  Only the first parameter set is used to initialize the decoder.  'avc3' specifically ignores these parameters for decoding, and only uses the inband parameters in each CVS. The constraint on not allowing the entropy coding mode to change during a track is a separate topic worth discussion.
