### ISSUE TITLE
2nd draft: 9.4.2.6 change shall statement on frame rate from track run box

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#63]
Comment 43: “Sample durations stored in the ISO Media Track Run Box SHALL determine the frame rate of a Track.”

Rephrase to say that the frame timing is defined by the file format layer, and not by anything in the video stream (e.g. fixed frame rate). Do we need to say that they must be the same (to allow easy conversion to transport streams, for example)? Probably not. But if not, we need a warning note.

ACTION: Make frame rate a factual statement, referencing part 12 or 15 requirement to use 'trun' sample durations and ignore elementary stream timing.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
done in CD
