### ISSUE TITLE
2nd draft: 9.5.3 Replace term "macroblock"

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#65]
Comment 45: “macroblocks encoded if the image height or width is not a multiple of 16 samples”

Fix the text to be applicable to both AVC, HEVC

Kilroy Hughes: We should say something about blocks and encoding trees – we want to be as general as possible. 16 would be fine. 

ACTION: Rephrase "macroblocks" to efficient block size for cropping. Generalize about video encoding.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
done in the CD
