### ISSUE TITLE
2nd draft: 9.6.2  multiple languages in CEA-608/708 in SEI messages 

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#68]
Bill May: Clarify the CEA-x08: what happens when there is a multiplex of languages by service numbers. Either there is only one language, or tie the language to the track and service ID.

When 608/708, not understood 1 track or multiple tracks one for each language, and inclusion of extended, can’t tie cc or service number, so I would recommend we either say one track box and all the language information is in the manifest or tie each language to each service.

May be solved in Part 30.

ACTION: Agree that this should be indicated in the manifest

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by ghost** [comment]
Adding language constraining to one Track box, and signaling of multiple services and languages in Manifests.

**Comment by mikedo** [comment]
I'm not sure this is the right answer.  708 is first a data structure that contains a 608 bitstream and/or a 708 bitstream.  A 608 bitstream is a multiplex of 0-4 caption services, 0-4 text services and 0-1 XDS packet streams. XDS packets may contain, among other things, language labels. A 708 bitstream is a multiplex of 0-31 caption services.

708 (and the tunneled 608) services are generally not discriminatable without the out of band signaling for language and other metadata (aspect ratio and "easy reader") as defined in 708-D section 4.5.  ATSC and SCTE signals this metadata in an MP2TS Caption Service Descriptor (CSD) as defined in ATSC A/65.

Manifest signaling is primarily for track selection. There is only one (video) track that contains the 708 data structure which will not be selected by caption metadata settings.

Arguably the caption service metadata should be at the segment/file layer signaling, not manifest.

Either way, the signaling needs to effectively mimic the A/65 CSD MP2TS descriptor contents for all caption services present - 608 + 708.

**Comment by irajs** [comment]
No change. When Part 30 addresses the presence of the CC in track, then CMAF use the solution.
