### ISSUE TITLE
2nd draft: 10.3.3 Sync Sample Box

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#69]
Section 10.3.3 Sync Sample Box

Contribution 304
Mentions the sync sample box.  However, the same would apply to video tracks, and as the note says the use (or otherwise) of it has no effect. Video tracks have an empty sync sample box to say that 'not everything is a sync sample'.  Ingo confirms. 

 ACTION: We need to have section 7 that the sync sample shall be present IF and Only IF not every sample is a sync sample.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by ghost** [comment]
Empty Sync sample box required for video to indicate all samples are not sync samples.
