### ISSUE TITLE
2nd draft: Section 10.4 General Constraints on Audio Codecs 

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#70]
Ingo: 10.4 (new).  Ingo finds this section, even 10.4.1, confusing. Comments welcome.
10.4.5: priming; 'packets' undefined, say access unit. and it seems to say that the desired audio is priming. "before it produces" is not right, it's "before the intended audio signal".

 ACTION: Info Hoffman to provide contribution to improve section 10.4.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by irajs** [comment]
addressed by Ingo
