### ISSUE TITLE
2nd draft: Section 10.5.3.2.4 AudioSpecificConfig

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#71]
Contribution 304

Is the intent that AAC-LC be stereo or mono? (Similarly but less strictly 10.5.3.2.1). Should the mono/stereo restriction go to the Annex (a profile)? Yes, the stereo restriction becomes a profile question.

ACTION: AAC-LC remove stereo constraints.  Constrain in Media Profile.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by dwsinger** [comment]
now says "♣   channelConfiguration = 1 (for HE-AACv2 or mono HE-AAC) or 2 (for stereo HE-AAC), or as appropriate for streams with more channels."
