### ISSUE TITLE
2nd draft: 10.5.6.2.1 Syntax and Values of Syntactic Elements 

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#72]
Does this actually prohibit PCE?  Ingo will check if it can be ignored. Problem with general requirements, and description of priming.  Ingo will comment.

Program_config_element wouldn’t expect decoder, required or not, packaging AAC stream, finding out that not included, hard to find. Can a PCE in stream, possible to ignore them?

ACTION: Ingo Hoffman to clarify answer.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by irajs** [comment]
Addressed by Ingo in CD
