### ISSUE TITLE
2nd draft: Annex A  CMAF Presentation and Media Profiles 

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#73]
Chris Poole (BBC): Changes to Table 5

In Annex A table 5, the EOTF column should be relabeled "Transfer characteristics" so as to be general enough to cover the ways in which the different schemes are defined (either scene-referred or display-referred).  It should contain "BT.709 OETF" or "BT.709 OETF, BT.2020 OETF" for the SDR profiles, not BT-1886, as the traditional TV system is defined by the OETF (see ITU-R BT.2390 section 3 for details).  The entry for HDR10 should say "ST-2084 EOTF".

Additionally, there should be a note added below Table 5 saying: Note: Where HDR content is being delivered using an HDR system that is backwards compatible with a non-HDR profile, the appropriate non-HDR profile and transfer characteristics should be signaled so that legacy and non-HDR players will recognize the content as being suitable for them to display.  The HDR capability in such cases can be indicated through the use of appropriate SEI messages, and also signaled in any associated manifests.

The HLG SDR scheme is standardized and will be in use by many broadcasters by the time the CMAF specification is published.  It is one of two HDR approaches (PQ/ST-2084 being the other) covered in the ITU-T report BT.2390 describing the forthcoming ITU-R HDR standard which will include those.  A new entry needs to be added to Annex A table 5 to cover HLG HDR, duplicating the entry for HDR10 but with "ARIB STD-B67 OETF" in the transfer characteristics column.  When the ITU-R standard is published that could be referenced here as well or instead.

Video media profiles.  Add HLG. 

Reduce table to only list columns that constrain MPEG profile/level, don't quote profile parameters.
Add Max bitrate independent of frame size?  What about 720P60 and HFR options in other profiles allowed with subsampled frames? 

Remove "@maxsize" from the frame rate column. What do we mean by frame rate? The closest composition timestamps are no closer than 1/frame-rate. We could allow 720p60 but note it's not possible at full frame size.

Mike Dolan: all the rows after the second are speculative. How do we decide what rows?  What is the criterion?

Decide: which columns to keep, some need to go. Add a row for HLG ('live' vs. 'pre-recorded')?  Bitrate should be max-bit-rate.

Need a note on content that is compatible with a non-HDR profile?

Pierre: the annex is really only about row 2. Why are the other rows here? We need to clarify what the other rows mean (see A.1 first few sentences). Mandatory and optional more clearly delineated. Put the mandatory one first?

Patrick Ladd: please clarify that cfhd is required. And saying you have to be in the table to be allowed in CMAF is clearly a non-starter.  What do these optional profiles mean?

DECIDE: Should any of the columns be removed and add a row for HLG since part of MPEG now. 
Scott L: BBC, backward compatibility, Cisco, talking to customers, SDR and HDR, high desire backward compatible format. 

ACTION: Consider criteria for inclusion of profiles. 
ACTION: Rename EOTF column as per BBC suggestion to ‘transfer characteristics’
ACTION: Remove @maxsize from frame rate column. Change bitrate to max-bit-rate.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by ghost** [comment]
Annex A and video Media Profiles table updated per last three action items.  No addition of HLG Media Profile lacking consensus on last AHG call documented above.
