### ISSUE TITLE
HDR signaling constraints in core video (May draft, 9.5.4)

### ISSUE THREAD

**Issue by mikedo** [irajs/CMAF#74]
Regarding:

"...the grading profile SHOULD be signaled by VUI and/or [ST2086] metadata in SEI messages contained in the sample entry ‘'avcC’' or ‘'hvcC’' box, and content descriptors in CMAF compliant Manifests."

It seems too early to be putting in HDR signaling constraints - this is at odds with the directive to focus on "widely deployed technology" and it is in an area where the signaling is still being standardized. I believe that the above text should be deleted. It could be moved to an optional profile (e.g. HDR10) so that it causes no harm, but that doesn't really address the problems.

**Comment by dwsinger** [comment]
filed on m38228/v2, we think

**Comment by poolec** [comment]
This issue was addressed at the 9th May call and the new agreed text is in #66.

**Comment by mikedo** [comment]
Addressed in MPEG m38555 accepted on 31-May-16.
