### ISSUE TITLE
Audio Out-of-band signaling (May draft, 10.4.10)

### ISSUE THREAD

**Issue by mikedo** [irajs/CMAF#75]
Regarding:

"CMAF Media Profiles for audio codecs SHALL prohibit encoding variations that place decoder inputs outside the CMAF Track."

As worded it seem very broad. As I understand the intent, it is not to preclude track selection items found in the manifest (e.g. language, video description) and personalization items for the decoder (e.g. dialog loudness, video description enabled).  I propose it be clarified as follows:

"CMAF Media Profiles for audio codecs SHALL prohibit encoding variations that place the audio decoder module inputs other than within the CMAF Track. Note: This does not preclude track selection metadata normally found in the manifest (e.g. language, video description) or personalization items (e.g. dialog loudness, video description enabled)."

**Comment by dwsinger** [comment]
filed on m38228/v2, we think

**Comment by ghost** [comment]
Recommended text used.
