### ISSUE TITLE
m38228/v2 Annex B and througout - "compatible" profiles

### ISSUE THREAD

**Issue by mikedo** [irajs/CMAF#76]
This is a follow-up to discussion in Paris and related to a couple of surgical edits on this topic found in #39 and #42.

The use of the term, "compatible" throughout the document has established a "second class" of media profiles to be defined external to this document. This distinction is unnecessary and creates a perception about the two classes that does not add anything. Profiles, including the ones defined in this document, either conform to the general codec provisions or they don't.  The ones that do conform are "compatible". The distinction is not about where they are defined, but to what they conform. All media profiles, regardless of where they are defined, have to conform to some core provisions.

The capitalized term, "CMAF Compatible Media Profiles" is used Annex B but not defined.  The term, "CMAF Media Profile" is defined and used to refer to apparently the same thing, e.g. 6.1.1, 10.4. There are other variations throughout the document that appear to be the same, e.g. 10.2 "CMAF Compatible Audio Media Profiles", 3.1 "compatible CMAF Tracks", etc.

I propose we:
1. Delete all uses of "compatible" where it means to distinguish between profiles defined in this document versus profiles defined in other documents; and
2. Change the definition of "CMAF Media Profile" to explicitly reference the provisions that establish a conformant profile, i.e.: "...for video, conforms to 9.1-9.2.2; for audio, conforms to 10.1-10.4; and for subtitles, conforms to [no core provisions currently defined for subtitles]"

**Comment by ghost** [comment]
Changed to CMAF Media Profiles throughout, to include Media Profiles defined in Annex A or by reference through Annex B.
