### ISSUE TITLE
m38228/v2 7.3.4 loss of content

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#77]
we feel that CMAF still falls a bit short on the subject of loss, and there are several restrictions that make this even harder. 

The main section that addresses loss is in Section 7.3.4, specifically note 1.

First, it states:
"Gaps in decode time would result in audio video synchronization errors because the ISO Base Media File Format calculates decode and presentation times as the sum of prior sample durations in a track."

While this is correct, the decode and presentation times can be calculated by use of the baseMediaDecodeTime in each fragment; the document later specifies that this should be used to calculate the times used during I-frame playback.

For short term loss, the following is stated:

"If audio or video frames are unavailable during recording, recorded samples may be extended in duration or filled with media data such as silent audio or repeated pictures."

Extending the duration within a fragment or even a segment is acceptable.  We would like to see this stated as mandatory for audio as well as video.

Inserting silence is problematic with a separate packager.  Repeating pictures would also be a problem; you could potentially move the last IDR frame forward, but it would be a skip backwards.  You could generate a black slate, but again, that would be extremely difficult to maintain.

However, a loss that extends across more than one segment is problematic with the rest of the definitions, specifically the ones that state:
- Each Track in a Switching Set SHALL have the same number of CMAF Fragments.
  There are potentially more problems with this statement, especially around having different GOPs for scene changes, but we should focus on this as it restricts loss.

With our existing workflow, there are ways that loss of more than a segment can occur; an encoder failure, and an inability to write a segment to disk.

We feel that in these situations, either writing silent audio, or repeating/generating video frames is not feasible.  

However, we feel that if CMAF allows us to generate empty segments (a fragment with a duration, but no video or audio sample data), this would be something that would be fairly simple to generate, and something that would be easy for a player to detect and deal with.

**Comment by ghost** [comment]
Specifying missing Segments is probably a delivery protocol issue, and specifying Segments without media samples is probably a file format issue.  
The CMAF spec was modified to say that if there is a discontinuity in the baseMediaDecodeTime of CMAF Fragments, that the BMDT determines the presentation time.  That means a player that doesn't receive an expected video Segment could resume playback on the next available video Segment without loss of A/V sync. How it avoids 404s, etc. is out of scope for CMAF. Whether ISOBMFF files can record BMDT gaps between movie fragments is an ISOBMFF issue, so the CMAF spec can't solve it, other than to recommend the available options, which it now does.
