### ISSUE TITLE
m38228/v2 baseMediaDecodeTime

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#79]
There are times that it seems that the base media decode time has to be the first presentation time, and I'm not sure how that can happen, or how that doesn't spread ripples through the entire presentation.  We tend to use startDTS of the next segment - DTS of the first sample as the duration.

Can you please give me an example of what exactly you mean here?

In addition, in section 7.3.5, it states:

 5.
The Track Fragment Box ('traf') SHALL contain one Track Fragment Decode Time Box ('tfdt') that indicates both the earliest sample presentation time in the Fragment and the earliest sample decode time (stored in the baseMediaDecodeTime field).

How can this happen?  14496-12 2015 only shows baseMediaDecodeTime.  How can that be earliest sample presentation time and the earliest sample decode time?

Doesn't this also mess thing up when you have missing samples at the start of the next segment?

**Comment by ghost** [comment]
How can this happen? 14496-12 2015 only shows baseMediaDecodeTime. How can that be earliest sample presentation time and the earliest sample decode time.? 

For long GOP video sequences, sample reordering is accomplished by composition time offsets in the 'trun' box. By using v1 'trun' and negative composition offsets, the composition time interval of each Fragment can be adjusted to equal its decode time interval.  If positive offsets are used with a v0 'trun', then the composition time interval of each Fragment will be delayed by a few frames relative to the decode time and other tracks, such as audio and video. In that case (v0 'trun'), an edit list is necessary during file playback to compensate for the composition delay. A Manifest can specify the composition/presentation time corresponding to the start of the Presentation, and can include the edit list duration in that value to prevent composition delay of the earliest presented sample.
