### ISSUE TITLE
m38228/v2 Annex G

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#80]
I feel that while the examples in G.4 are good (although I would move the EXT-X-MEDIA's TYPE attribute so it is first and GROUP-ID so it is second), the rest can lead to some misinterpretation.

Particularly around video renditions and selection sets.

I think that this section might be better served by using the format that we used in the HLS spec, and discussing first the media playlists (and how they relate to CMAF) and then the master playlists.

Also, I'd like to see the master playlists discussion use the terminology used in the HLS specification,  rather than the tags.  I feel that we have a good set of terms in the HLS spec and have well defined them. Terms like "Variant Streams", "Renditions" and "Rendition Groups" can be used to make things clearer, even if we have to prepend HLS to the beginning.

I would be glad to take a stab at re-writing this section, or work with whoever to bring it more in line with the HLS specification.

**Comment by dwsinger** [comment]
who is "I"?

**Comment by dwsinger** [comment]
(Bill May is "I"). We conclude that the binding annexes (including the DASH annex) should not be in the CMAF spec., and need to be normatively published somewhere else. Possibilities include in the DASH and HLS specs., as a DASH-IF document, as a CTA WAVE document. It's also possible to produce an ISO Technical Report to pull all this together, referring to the normative documents and giving guidelines. (A decision needs to be made).
