### ISSUE TITLE
Clearly state whether Tracks must have data for the entire Presentation duration

### ISSUE THREAD

**Issue by sandersaares** [irajs/CMAF#81]
There is a common situation currently occurring with DASH presentations where packagers create on-demand content where the different tracks end at different times (some segments are either 404s or contain no samples after a certain point for certain tracks). There are differing interpretations about whether this is valid or not.

It would be good if CMAF could eliminate the potential for such different interpretations here by having a single clear statement in the spec stating either something like "Tracks must contain contiguous samples covering at least the timeline between the start of the Presentation and the end of the Presentation" (if the CMAF authors intend this to be the valid interpretation) or something else that clarifies the intended interpretation.

It seems to me that the current draft implies that there can't be parts of the timeline with missing samples but having it made an explicit statement would help eliminate any human error in interpreting the nature of things.

**Comment by ghost** [comment]
Sections 7.3.8, 7.3.9, 7.3.10 have been updated to clarify the duration of Tracks in a Switching Set, Selection Set, and Presentation.
