### ISSUE TITLE
m38226/V3: Section 7.2 codec subparameters

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#82]
Clarify the codec sub-parameters and profiles

**Comment by dwsinger** [comment]
Don't understand. This section is about brands.

**Comment by cconcolato** [comment]
I think the idea was to recommend to use of the profile sub-parameter to signal brands.

**Comment by dwsinger** [comment]
ah, "Note that the profiles MIME parameter can be used to signal the brands, as defined in RFC 6381"?

**Comment by cconcolato** [comment]
Yes, but since brands are quite important in CMAF, we could even discuss whether the text should use SHOULD and not be a note. But that's good for now.

**Comment by dwsinger** [comment]
Cyril says it's good for now, closing
