### ISSUE TITLE
m38226/V3: 8.2.2.1

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#86]
the sample aux box is added and several places it is referenced. Please make sure that it covers both cases.

**Comment by dwsinger** [comment]
both what?

**Comment by ghost** [comment]
I think this meant sample aux info can be stored in both ‘senc’ and ‘uuid’ boxes.
That change was made.

Kilroy Hughes | Senior Digital Media Architect |Windows Azure Media Services | Microsoft Corporation
[cid:image001.png@01CDABBA.71FD8800]http://www.windowsazure.com/media

**Comment by dwsinger** [comment]
closing as addressed by Kilroy
