### ISSUE TITLE
Section 6.1.8- CMF Presentation and Timing Model- Discontinuity

### ISSUE THREAD

**Issue by YasserSyed** [irajs/CMAF#9]
How does a discontinuity affect the creation of a CMAF track?

**Comment by cconcolato** [comment]
In 6.1.8 (http://cconcolato.github.io/cmaf/index.html#cmaf-presentation-and-timing-model), it says:

> Discontinuities in CMAF Track timelines are considered a new CMAF Track in a new CMAF Presentation that must specify the CMAF Track’s decode time at the start of the CMAF Presentation (similar to a DASH Period).

**Comment by dwsinger** [comment]
filed on w15947 (San Diego output)

**Comment by dwsinger** [comment]
clarified in 38228 "Discontinuities in CMAF Track timelines are considered a new CMAF Track in a new CMAF Presentation. A Manifest must specify the CMAF Track decode time at the start of each CMAF Presentation."
